/* global window */
// Urbanova listings — sve iz Beograda za sada
const LISTINGS = [
  {
    id: "urb-2401",
    title: "Penthouse sa pogledom na Hram",
    type: "Stan",
    deal: "Prodaja",
    city: "Beograd",
    district: "Vračar",
    address: "Krunska, Vračar",
    price: 485000,
    sqm: 142,
    rooms: 4,
    bathrooms: 2,
    floor: "6/6",
    year: 2023,
    heating: "Etažno gas",
    parking: "2 mesta",
    status: "Novo",
    new: true,
    featured: true,
    lat: 52, lng: 48,
    img: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=75&auto=format&fit=crop",
    desc: "Svetli dvoetažni penthouse na mirnoj lokaciji u srcu Vračara. Terasa od 38m² sa pogledom na Hram Svetog Save, francuski balkon, prirodno osvetljenje tokom celog dana. Završni radovi na najvišem nivou — hrastov parket, italijanska keramika, aluminijumska stolarija sa troslojnim staklom.",
    features: ["Terasa 38m²", "Panoramski pogled", "Dvoetažni", "Liftovi 2×", "Klima inverter", "Alarm i video nadzor", "Smart home", "Podno grejanje"],
    agent: "Ana Jovanović"
  },
  {
    id: "urb-2402",
    title: "Vila sa bazenom na Dedinju",
    type: "Kuća",
    deal: "Prodaja",
    city: "Beograd",
    district: "Dedinje",
    address: "Užička, Dedinje",
    price: 1250000,
    sqm: 380,
    rooms: 6,
    bathrooms: 4,
    floor: "P+1+Pk",
    year: 2019,
    heating: "Toplotna pumpa",
    parking: "Garaža 2×",
    status: "Ekskluzivno",
    featured: true,
    lat: 35, lng: 30,
    img: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&q=75&auto=format&fit=crop",
    desc: "Reprezentativna vila u mirnoj ulici Dedinja. Okućnica od 820m² sa bazenom 12×5m, zasađenim vrtom i prostorom za roštilj. Dnevna zona otvorenog plana, velika kuhinja sa ostrvom, master suite sa garderobom i kupatilom od 18m².",
    features: ["Bazen 12×5m", "Okućnica 820m²", "Garaža za 2 auta", "Podno grejanje", "Klima", "Alarm", "Kamin", "Smart home", "Vinski podrum"],
    agent: "Marko Petrović"
  },
  {
    id: "urb-2403",
    title: "Dvosoban stan, West 65",
    type: "Stan",
    deal: "Prodaja",
    city: "Beograd",
    district: "Novi Beograd",
    address: "Bulevar AVNOJ-a, Novi Beograd",
    price: 248000,
    sqm: 62,
    rooms: 2,
    bathrooms: 1,
    floor: "12/23",
    year: 2022,
    heating: "Daljinsko",
    parking: "1 mesto",
    status: "Useljivo",
    new: true,
    featured: true,
    lat: 48, lng: 18,
    img: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&q=75&auto=format&fit=crop",
    desc: "Moderan dvosoban stan u kompleksu West 65, sa pogledom na Adu Ciganliju. Kupljen od investitora, nikad nije useljen. Kuhinja po meri, italijanska keramika.",
    features: ["Pogled na Adu", "Parking mesto", "Klima", "Lift", "Portirnica 24/7", "Fitnes", "Spa"],
    agent: "Ana Jovanović"
  },
  {
    id: "urb-2404",
    title: "Trosoban, Stari grad",
    type: "Stan",
    deal: "Prodaja",
    city: "Beograd",
    district: "Stari grad",
    address: "Gospodar Jevremova, Stari grad",
    price: 325000,
    sqm: 94,
    rooms: 3,
    bathrooms: 2,
    floor: "3/5",
    year: 1936,
    heating: "Etažno gas",
    parking: "Ne",
    status: "Renovirano",
    featured: true,
    lat: 42, lng: 44,
    img: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1200&q=75&auto=format&fit=crop",
    desc: "Austrougarska arhitektura, visoki plafoni 3.4m, originalne štukature sačuvane i restaurirane. Kompletna rekonstrukcija 2023. godine uz poštovanje originalnog duha prostora.",
    features: ["Visoki plafoni 3.4m", "Štukature", "Renovirano 2023", "Francuski balkon", "Etažno grejanje", "Originalna stolarija"],
    agent: "Jelena Đurić"
  },
  {
    id: "urb-2405",
    title: "Četvorosoban, Skadarlija",
    type: "Stan",
    deal: "Prodaja",
    city: "Beograd",
    district: "Stari grad",
    address: "Skadarska, Stari grad",
    price: 395000,
    sqm: 118,
    rooms: 4,
    bathrooms: 2,
    floor: "2/4",
    year: 1924,
    heating: "Etažno",
    parking: "Podzemna garaža",
    status: "Novo",
    new: true,
    lat: 46, lng: 50,
    img: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=75&auto=format&fit=crop",
    desc: "Ekskluzivna nekretnina u boemskom delu grada. Potpuno rekonstruisan stan u zgradi zaštićenog kulturnog dobra. Balkon sa pogledom na staru kaldrmu Skadarlije.",
    features: ["Kaldrma pogled", "Podzemna garaža", "Renovirano 2024", "Visoki plafoni", "Parket hrast"],
    agent: "Marko Petrović"
  },
  {
    id: "urb-2406",
    title: "Jednoiposoban, Zemun Kej",
    type: "Stan",
    deal: "Izdavanje",
    city: "Beograd",
    district: "Zemun",
    address: "Kej Oslobođenja, Zemun",
    price: 850,
    sqm: 48,
    rooms: 1.5,
    bathrooms: 1,
    floor: "2/4",
    year: 2020,
    heating: "Etažno gas",
    parking: "1 mesto",
    status: "Dostupno",
    lat: 20, lng: 22,
    img: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&q=75&auto=format&fit=crop",
    desc: "Komforan stan uz sam Kej, namešten premium opremom. Pogled na Dunav. Idealno za 1-2 osobe.",
    features: ["Pogled na Dunav", "Namešteno", "Klima", "Mašina za veš i sudove", "Parking"],
    agent: "Jelena Đurić"
  },
  {
    id: "urb-2407",
    title: "Loft u Cetinjskoj",
    type: "Stan",
    deal: "Prodaja",
    city: "Beograd",
    district: "Dorćol",
    address: "Cetinjska, Dorćol",
    price: 278000,
    sqm: 85,
    rooms: 2,
    bathrooms: 1,
    floor: "4/4",
    year: 1928,
    heating: "Etažno",
    parking: "Ne",
    status: "Renovirano",
    lat: 44, lng: 54,
    img: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=75&auto=format&fit=crop",
    desc: "Potkrovni loft u srcu kulturne zone. Vidljive grede, otvoreni plan, velika dvorišna terasa.",
    features: ["Terasa 22m²", "Vidljive grede", "Otvoreni plan", "Renovirano"],
    agent: "Ana Jovanović"
  },
  {
    id: "urb-2408",
    title: "Poslovni prostor, Nemanjina",
    type: "Poslovni",
    deal: "Izdavanje",
    city: "Beograd",
    district: "Savski venac",
    address: "Nemanjina, Savski venac",
    price: 3200,
    sqm: 210,
    rooms: 8,
    bathrooms: 3,
    floor: "2/5",
    year: 2015,
    heating: "Centralno",
    parking: "4 mesta",
    status: "Dostupno",
    lat: 58, lng: 40,
    img: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&q=75&auto=format&fit=crop",
    desc: "Reprezentativan kancelarijski prostor u blizini Zgrade Vlade. Open space koncept sa 3 sale za sastanke.",
    features: ["Open space", "3 sale za sastanke", "Parking 4 mesta", "Klima", "Server room", "Kuhinja"],
    agent: "Marko Petrović"
  },
  {
    id: "urb-2409",
    title: "Kuća na Banovom brdu",
    type: "Kuća",
    deal: "Prodaja",
    city: "Beograd",
    district: "Čukarica",
    address: "Požeška, Banovo brdo",
    price: 420000,
    sqm: 210,
    rooms: 5,
    bathrooms: 3,
    floor: "P+1",
    year: 2016,
    heating: "Gas",
    parking: "Garaža 2×",
    status: "Useljivo",
    lat: 62, lng: 28,
    img: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=75&auto=format&fit=crop",
    desc: "Porodična kuća sa vrtom od 4 ara. Dnevna zona otvorenog plana, velika kuhinja, 4 spavaće sobe, radna soba. Tih kraj, 10 minuta do centra.",
    features: ["Vrt 4 ara", "Garaža 2 auta", "Terasa", "Podno grejanje", "Alarm", "4 spavaće sobe"],
    agent: "Jelena Đurić"
  }
];

// expose
window.LISTINGS = LISTINGS;
// sve cene su u EUR u bazi; konvertujemo u RSD za prikaz (kurs ~117)
const EUR_TO_RSD = 117;
const fmtRsd = (n) => n.toLocaleString("sr-RS").replace(/,/g, ".");
window.fmtPrice = (p, deal) => {
  const rsd = p * EUR_TO_RSD;
  if (deal === "Izdavanje") return `${fmtRsd(rsd)} RSD/mes`;
  if (rsd >= 1000000000) return `${(rsd/1000000000).toFixed(2).replace(/\.?0+$/,"")} mlrd RSD`;
  if (rsd >= 1000000) return `${(rsd/1000000).toFixed(1).replace(/\.?0+$/,"")}M RSD`;
  return `${fmtRsd(rsd)} RSD`;
};
window.fmtPriceSqm = (p, sqm, deal) => {
  if (deal === "Izdavanje") return null;
  const perM2 = Math.round((p * EUR_TO_RSD) / sqm);
  return `${fmtRsd(perM2)} RSD/m²`;
};
